"""Process management for MediaMTX and looping FFmpeg RTSP publishers."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import shutil
import subprocess
import time
from typing import Iterable

from .config import CameraConfig, SimulatorConfig


RUNTIME_DIR_NAME = ".runtime"


class ProcessStartError(RuntimeError):
    """Raised when a required process cannot be started."""


@dataclass
class ManagedProcess:
    name: str
    command: list[str]
    process: subprocess.Popen
    started_at: float

    @property
    def running(self) -> bool:
        return self.process.poll() is None

    @property
    def exit_code(self) -> int | None:
        return self.process.poll()

    def stop(self, timeout: float = 5.0) -> None:
        if not self.running:
            return
        self.process.terminate()
        try:
            self.process.wait(timeout=timeout)
        except subprocess.TimeoutExpired:
            self.process.kill()
            self.process.wait(timeout=timeout)


def executable_exists(command: str | Path) -> bool:
    command_text = str(command)
    return Path(command_text).is_file() or shutil.which(command_text) is not None


def write_mediamtx_config(config: SimulatorConfig) -> Path:
    """Generate a minimal, RTSP-only MediaMTX configuration for enabled paths."""
    runtime_dir = config.root / RUNTIME_DIR_NAME
    runtime_dir.mkdir(exist_ok=True)
    destination = runtime_dir / "mediamtx.generated.yml"

    lines = [
        "# Generated by KAVACH RTSP Simulator. Do not edit; change config.yaml.",
        "logLevel: info",
        "logDestinations: [stdout]",
        "api: false",
        "metrics: false",
        "pprof: false",
        "playback: false",
        "rtsp: true",
        "rtspTransports: [tcp]",
        'rtspEncryption: "no"',
        f"rtspAddress: {config.server.listen_address}",
        "rtmp: false",
        "hls: false",
        "webrtc: false",
        "srt: false",
        "moq: false",
        "pathDefaults:",
        "  source: publisher",
        "  overridePublisher: true",
        "paths:",
    ]
    for camera in config.enabled_cameras:
        lines.extend((f"  {camera.stream_path}:", "    source: publisher"))
    destination.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return destination


def mediamtx_command(config: SimulatorConfig, generated_config: Path) -> list[str]:
    return [str(config.tools.mediamtx_path), str(generated_config)]


def publisher_command(config: SimulatorConfig, camera: CameraConfig) -> list[str]:
    """Build a real-time, endlessly looping FFmpeg RTSP publish command."""
    command = [
        config.tools.ffmpeg_path,
        "-hide_banner",
        "-loglevel", config.publisher.log_level,
        "-nostdin",
        "-re",
        "-stream_loop", "-1",
        "-i", str(camera.source),
        "-map", "0:v:0",
        "-an",  # CCTV presentation feeds need video only; avoids audio codec surprises.
    ]
    if config.publisher.video_codec == "copy":
        command.extend(("-c:v", "copy"))
    else:
        command.extend((
            "-c:v", "libx264",
            "-preset", config.publisher.preset,
            "-tune", "zerolatency",
            "-crf", str(config.publisher.crf),
            "-pix_fmt", "yuv420p",
        ))
    command.extend((
        "-f", "rtsp",
        "-rtsp_transport", "tcp",
        "-muxdelay", "0.1",
        "-muxpreload", "0",
        f"rtsp://127.0.0.1:{config.server.port}/{camera.stream_path}",
    ))
    return command


class SimulatorProcesses:
    """Own MediaMTX plus independently restartable FFmpeg publishers."""

    def __init__(self, config: SimulatorConfig):
        self.config = config
        self.server: ManagedProcess | None = None
        self.publishers: dict[str, ManagedProcess] = {}

    def start_server(self) -> ManagedProcess:
        if self.server and self.server.running:
            return self.server
        if not self.config.tools.mediamtx_path.is_file():
            raise ProcessStartError(f"MediaMTX executable not found: {self.config.tools.mediamtx_path}")
        generated = write_mediamtx_config(self.config)
        self.server = self._start("MediaMTX", mediamtx_command(self.config, generated))
        return self.server

    def start_camera(self, camera: CameraConfig) -> ManagedProcess:
        if not executable_exists(self.config.tools.ffmpeg_path):
            raise ProcessStartError(
                f"FFmpeg executable not found: {self.config.tools.ffmpeg_path}. "
                "Install FFmpeg or set tools.ffmpeg_path in config.yaml."
            )
        if not camera.source.is_file():
            raise ProcessStartError(f"{camera.id}: source video not found: {camera.source}")
        existing = self.publishers.get(camera.id)
        if existing and existing.running:
            return existing
        managed = self._start(camera.id, publisher_command(self.config, camera))
        self.publishers[camera.id] = managed
        return managed

    def start_publishers(self) -> list[ManagedProcess]:
        return [self.start_camera(camera) for camera in self.config.enabled_cameras]

    def restart_stopped_publishers(self) -> list[str]:
        """Restart a publisher that stopped unexpectedly; return restarted IDs."""
        restarted: list[str] = []
        for camera in self.config.enabled_cameras:
            process = self.publishers.get(camera.id)
            if process is not None and not process.running:
                self.start_camera(camera)
                restarted.append(camera.id)
        return restarted

    def stop_camera(self, camera_id: str) -> bool:
        process = self.publishers.get(camera_id)
        if process is None:
            return False
        process.stop()
        return True

    def stop_all(self) -> None:
        for process in list(self.publishers.values()):
            process.stop()
        if self.server is not None:
            self.server.stop()

    @staticmethod
    def _start(name: str, command: list[str]) -> ManagedProcess:
        try:
            process = subprocess.Popen(
                command,
                cwd=str(Path(__file__).resolve().parents[1]),
                stdin=subprocess.DEVNULL,
                stdout=None,
                stderr=None,
            )
        except OSError as exc:
            raise ProcessStartError(f"Could not start {name}: {exc}") from exc
        return ManagedProcess(name=name, command=command, process=process, started_at=time.monotonic())


def format_command(command: Iterable[str]) -> str:
    """Readable command display; preserves paths containing spaces."""
    return " ".join(f'"{part}"' if " " in part else part for part in command)
